/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luxuan' at '4/15/18 11:09 AM' with Gradle 2.14.1
 *
 * @author luxuan, @date 4/15/18 11:09 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
