//import org.junit.Test;
//import static org.junit.Assert.*;
//
///*
// * This Java source file was auto generated by running 'gradle init --type java-library'
// * by 'luxuan' at '4/15/18 11:09 AM' with Gradle 2.14.1
// *
// * @author luxuan, @date 4/15/18 11:09 AM
// */
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
